apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: ufc
  name: pv-docker-registry
spec:
  storageClassName: ""
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: /mnt/data/pv-docker-registry
    type: ""
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 172.19.157.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ufc
  name: pvc-docker-registry
spec:
  # It's necessary to specify "" as the storageClassName
  # so that the default storage class won't be used, see
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  storageClassName: ""
  volumeName: pv-docker-registry
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
